version: '3'
services:

  redisstack:
    image: redis/redis-stack:latest
    container_name: redisstack
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  redisinsight:
    image: "redislabs/redisinsight:latest"
    container_name: redisinsight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis
